### ISSUE TITLE
Build only one binary on Windows instead of two

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-build#19]
Currently, the Windows build generates two .exe (one in the main Parsec folder, one in core/). At execution, the first one execs the second one by launching `core/parsec.exe core gui`.
This causes problems when trying to pin the app to the taskbar, as it's the second .exe that gets pinned, not the first one.
Ideally, we should only have one .exe with the correct Parsec icon that launches the GUI when no arguments are given.

**Comment by frossigneux** [comment]
https://github.com/Scille/parsec-build/pull/22
