### ISSUE TITLE
Remove mountpoint from Windows navigation bar on deinstallation

### ISSUE THREAD

**Issue by Max-7** [Scille/parsec-build#20]
**Keys and values that will have to be removed when uninstalling Parsec on Windows**

HKEY_CURRENT_USER\Software\Classes\CLSID\\{6C37F945-7EFC-480A-A444-A6D44A3D107F}\
HKEY_CURRENT_USER\Software\Wow6432Node\CLSID\\{6C37F945-7EFC-480A-A444-A6D44A3D107F}\
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\\{6C37F945-7EFC-480A-A444-A6D44A3D107F}\
HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\HideDesktopIcons\NewStartPanel\\{6C37F945-7EFC-480A-A444-A6D44A3D107F}

**Comment by frossigneux** [comment]
https://github.com/Scille/parsec-build/commit/c24bd49b9805f4ab2f76a1c2a435523ceddbaeb2
