### ISSUE TITLE
Problème de désinstallation

### ISSUE THREAD

**Issue by PhClermontScille** [Scille/parsec-build#30]
Système : Windows 10 Pro version 1809. Ecran +/- 22" 
Version PARSEC déjà installée: 1.1.2
Objectif: répondre à une invitation de Thierry à rejoindre une organisation, puis partager un fichier
1. Le client parsec se lance (process en arrère-plan), mais pas de GUI (et donc pas de signalement de nouvelle version 1.2.1)
2. Je lance la désinstallation de PARSEC (=1.1.2). -> OK
3. Je telecharge 1.2.1 de Github 64b. Problèmes de signalement de logiciel dangereux par Windows Defender et Norton, pour mémoire. A l'install, erreur : ne peut écraser le fichier parsec.exe.
En fait, le process 1.1.2 n'a pas été tué. Il empeche la suppression de son exécutable.
Après assassinat manuel, ok pour le nouveau lancement install.

**Comment by touilleMan** [comment]
Il y a eu un changement du système s'occupant de tuer le processus parsec entre les version 1.1.2 et 1.2.0 (du coup l'installer de la 1.2.0 n'arrive pas à tuer un process avec une version >1.2.0)

Ça ne devrait plus arriver avec les version plus récentes
